import { AdminConfig, INITIAL_ADMIN_CONFIG, StudyResult, UserProfile, INITIAL_USER, PersonalNote, Feedback, Devotional } from './types';

const KEYS = {
  CONFIG: 'app_config',
  USER: 'app_user',
  STUDIES: 'app_studies',
  NOTES: 'app_personal_notes',
  ROLE: 'app_role',
  THEME: 'app_theme',
  FEEDBACKS: 'app_feedbacks'
};

export const CoreStorage = {
  // Config (Admin writes, Client reads)
  saveConfig: (config: AdminConfig) => {
    localStorage.setItem(KEYS.CONFIG, JSON.stringify(config));
  },
  loadConfig: (): AdminConfig => {
    const data = localStorage.getItem(KEYS.CONFIG);
    return data ? JSON.parse(data) : INITIAL_ADMIN_CONFIG;
  },

  // User Profile
  saveUser: (user: UserProfile) => {
    localStorage.setItem(KEYS.USER, JSON.stringify(user));
  },
  loadUser: (): UserProfile => {
    const data = localStorage.getItem(KEYS.USER);
    return data ? JSON.parse(data) : INITIAL_USER;
  },

  // Studies (Generated by AI)
  saveStudy: (study: StudyResult) => {
    const current = CoreStorage.loadStudies();
    const updated = [study, ...current];
    localStorage.setItem(KEYS.STUDIES, JSON.stringify(updated));
  },
  loadStudies: (): StudyResult[] => {
    const data = localStorage.getItem(KEYS.STUDIES);
    return data ? JSON.parse(data) : [];
  },

  // Personal Notes (Tools)
  saveNote: (note: PersonalNote) => {
    const notes = CoreStorage.loadNotes();
    const index = notes.findIndex(n => n.id === note.id);
    let updated;
    if (index >= 0) {
      updated = [...notes];
      updated[index] = note;
    } else {
      updated = [note, ...notes];
    }
    localStorage.setItem(KEYS.NOTES, JSON.stringify(updated));
  },
  loadNotes: (): PersonalNote[] => {
    const data = localStorage.getItem(KEYS.NOTES);
    return data ? JSON.parse(data) : [];
  },
  deleteNote: (id: string) => {
    const notes = CoreStorage.loadNotes();
    const updated = notes.filter(n => n.id !== id);
    localStorage.setItem(KEYS.NOTES, JSON.stringify(updated));
  },

  // Feedbacks
  saveFeedback: (feedback: Feedback) => {
    const items = CoreStorage.loadFeedbacks();
    const updated = [feedback, ...items];
    localStorage.setItem(KEYS.FEEDBACKS, JSON.stringify(updated));
  },
  loadFeedbacks: (): Feedback[] => {
    const data = localStorage.getItem(KEYS.FEEDBACKS);
    return data ? JSON.parse(data) : [];
  },
  
  // Devotionals (Mock for this version, usually fetched from backend/admin)
  loadDevotionals: (): Devotional[] => {
    return [
      {
        id: '1',
        title: 'Confiança Inabalável',
        verse: 'Salmos 125:1',
        content: 'Os que confiam no Senhor são como o monte Sião, que não se abala, mas permanece para sempre. Hoje, lembre-se que sua estabilidade não vem das circunstâncias, mas de Deus.',
        date: new Date().toISOString()
      },
      {
        id: '2',
        title: 'A Paz de Cristo',
        verse: 'João 14:27',
        content: 'Deixo-vos a paz, a minha paz vos dou. Não a dou como o mundo a dá. Não se turbe o vosso coração, nem se atemorize. Respire fundo e receba essa paz agora.',
        date: new Date(Date.now() - 86400000).toISOString()
      }
    ];
  },

  // Theme
  saveTheme: (theme: 'light' | 'dark') => {
    localStorage.setItem(KEYS.THEME, theme);
  },
  loadTheme: (): 'light' | 'dark' => {
    return (localStorage.getItem(KEYS.THEME) as 'light' | 'dark') || 'light';
  },

  // Auth Role (Simple for this version)
  isAdmin: (): boolean => {
    return localStorage.getItem(KEYS.ROLE) === 'admin';
  },
  setAdmin: (isAdmin: boolean) => {
    if (isAdmin) localStorage.setItem(KEYS.ROLE, 'admin');
    else localStorage.removeItem(KEYS.ROLE);
  }
};